language: c
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - g++
      - gfortran
      - valgrind
      - csh
      - g++-multilib
      - gcc-multilib

branches:
  only:
    - master

before_install:
  # Configure environment.
  - source devtools/ci/install.sh
  - export PYTHONUNBUFFERED=true
  # Unpack encrypted OpenEye license file
  - if [ ! $TRAVIS_PULL_REQUEST ]; then openssl aes-256-cbc -K $encrypted_dc22cc99e02f_key -iv $encrypted_dc22cc99e02f_iv -in oe_license.txt.enc -out oe_license.txt -d; fi

install:

script:
  # Add omnia channel
  - conda config --add channels http://conda.anaconda.org/omnia
  # this builds the binary, unpacks it, and runs limited tests that don't have access to external dependencies
  - conda build devtools/conda-recipe
  # Install package prerequisites
  - conda config --add channels https://conda.anaconda.org/rdkit
  - conda install --yes --quiet nose
  - conda install --yes --quiet packmol
  # Install OpenEye toolkit
  - pip install $OPENEYE_CHANNEL openeye-toolkits
  # Install the package and test it
  - conda install --yes --quiet openmoltools-dev
  - nosetests openmoltools -v -a '!slow'

env:
  matrix:
    # OpenEye production
    - python=2.7  CONDA_PY=27  OPENEYE_CHANNEL="-i https://pypi.anaconda.org/openeye/channel/simple"
    - python=3.3  CONDA_PY=33  OPENEYE_CHANNEL="-i https://pypi.anaconda.org/openeye/channel/simple"
    - python=3.4  CONDA_PY=34  OPENEYE_CHANNEL="-i https://pypi.anaconda.org/openeye/channel/simple"
    # OpenEye beta
    - python=2.7  CONDA_PY=27  OPENEYE_CHANNEL="--pre -i https://pypi.anaconda.org/openeye/channel/beta/simple"
    - python=3.3  CONDA_PY=33  OPENEYE_CHANNEL="--pre -i https://pypi.anaconda.org/openeye/channel/beta/simple"
    - python=3.4  CONDA_PY=34  OPENEYE_CHANNEL="--pre -i https://pypi.anaconda.org/openeye/channel/beta/simple"

  global:
    # Location of decrypted OpenEye license file
    - OE_LICENSE="$HOME/oe_license.txt"
    # encrypted BINSTAR_TOKEN for push of dev package to binstar
    - secure: "gHW0bvR0blzHALWiODT0t+eg2tpXXIx8uR3ZNFjldDbuLqcGRs0UCZzy2J42/Yl1OHcjkN4SRZGz1EBsF6DRSI9XbSxOy/FH3kwZwr9ROOBYQ50/6JLwsN2iZnw6EPpjfpx/1pehRu49ZKU3tM8N7MA61OR/dm8ExAynSxJHZME="

after_success:
  - echo "after_success"
  - source devtools/ci/after_success.sh
