language: c

branches:
  only:
    - master

install:
  - source devtools/ci/install.sh
  - export PYTHONUNBUFFERED=true

script:
  # this builds the binary, unpacks it, and runs the tests
  - conda build devtools/conda-recipe

env:
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.3  CONDA_PY=33
    - python=3.4  CONDA_PY=34

  global:
    # encrypted BINSTAR_TOKEN for push of dev package to binstar
    - secure: "gHW0bvR0blzHALWiODT0t+eg2tpXXIx8uR3ZNFjldDbuLqcGRs0UCZzy2J42/Yl1OHcjkN4SRZGz1EBsF6DRSI9XbSxOy/FH3kwZwr9ROOBYQ50/6JLwsN2iZnw6EPpjfpx/1pehRu49ZKU3tM8N7MA61OR/dm8ExAynSxJHZME="

after_success:
  - echo "after_success"
  - source devtools/ci/after_sucess.sh
