language: c

branches:
  only:
    - master

before_install:
  # Configure environment.
  - source devtools/ci/install.sh
  - export PYTHONUNBUFFERED=true
  # Unpack encrypted OpenEye license file
  - openssl aes-256-cbc -K $encrypted_dc22cc99e02f_key -iv $encrypted_dc22cc99e02f_iv -in oe_license.txt.enc -out oe_license.txt -d

install:

script:
  # this builds the binary, unpacks it, and runs limited tests that don't have access to external dependencies
  - conda build devtools/conda-recipe
  # Install pacakge prerequisites
  - conda install --yes nose
  - pip install --pre -i https://pypi.binstar.org/openeye/simple openeye-toolkits
  # Now install the package and test it
  - conda install --yes --quiet openmoltools-dev
  - nosetests openmoltools -v -a '!slow'

env:
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.3  CONDA_PY=33
    - python=3.4  CONDA_PY=34

  global:
    # Location of decrypted OpenEye license file
    - OE_LICENSE="$HOME/oe_license.txt"
    # encrypted BINSTAR_TOKEN for push of dev package to binstar
    - secure: "gHW0bvR0blzHALWiODT0t+eg2tpXXIx8uR3ZNFjldDbuLqcGRs0UCZzy2J42/Yl1OHcjkN4SRZGz1EBsF6DRSI9XbSxOy/FH3kwZwr9ROOBYQ50/6JLwsN2iZnw6EPpjfpx/1pehRu49ZKU3tM8N7MA61OR/dm8ExAynSxJHZME="

after_success:
  - echo "after_success"
  - source devtools/ci/after_sucess.sh
