language: c

branches:
  only:
    - master

install:
  - source devtools/ci/install.sh
  - export PYTHONUNBUFFERED=true

script:
  # this builds the binary, unpacks it, and runs the tests
  - conda build devtools/conda-recipe

env:
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.3  CONDA_PY=33
    - python=3.4  CONDA_PY=34

  global:
    # encrypted BINSTAR_TOKEN for push of dev package to binstar
    - secure: "cuLLKOyxf1izHMIlGHRGi7W6soy1VhehQ2xhq2+q1EKLNaUvPLbJgrdut06jS4Tw9/8cwLEeG3WXA5RUrI/3AWmP/dq5gld5ON+7OMTFqO/5nXhE+IOcDJkNSFh04lBeEjaalve+WGX4q/Johy35YJG7jp88FWjXQRrE6P2u4Bw="

after_success:
  - echo "after_success"
  - source devtools/ci/after_sucess.sh
