language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

# Will only test on Linux be default, special includes are needed for OSX
python:
    - 3.5
    - 3.6

matrix:
  include:
    # Extra includes for OSX since python language is not available by default on OSX
    - os: osx
      language: generic
      env: PYTHON_VER=3.5
    - os: osx
      language: generic
      env: PYTHON_VER=3.6

env:
  global:
    # Location of decrypted OpenEye license file
    - OE_LICENSE="$HOME/oe_license.txt"

branches:
  only:
    - master

before_install:
  # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a
  # Install Conda and dependencies
  - source devtools/travis-ci/install.sh
  - python -V
  # Unpack encrypted OpenEye license file
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ] ; then openssl aes-256-cbc -K $encrypted_789b8a51897c_key -iv $encrypted_789b8a51897c_iv -in oe_license.txt.enc -out $HOME/oe_license.txt -d; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" == false ] ; then echo "OpenEye license will not be installed in pull request."; fi

install:
  # Create test environment for package
  - conda create --yes -n test python=$PYTHON_VER pip pytest pytest-cov
  - source activate test
  - conda install --yes codecov  # Only available in conda-forge channel or pip
  # Install the OpenEye toolkit
  - conda install --yes -c openeye openeye-toolkits && python -c "import openeye; print(openeye.__version__)"
  # Install other testing dependencies
  - conda install --yes --quiet nose nose-timer
  - conda install --yes --quiet openmmtools
  - conda install --yes --quiet packmol
  - conda install --yes --quiet rdkit
  # Build the conda package
  - conda build --python=$PYTHON_VER devtools/conda-recipe
  - conda install --yes --use-local openmoltools-dev

script:
  #- pytest -v --cov=openmoltools --cov-config setup.cfg openmoltools/tests/
  # Use nosetests to get some idea of what is failing
  - nosetests -vv --nocapture openmoltools/tests

notifications:
  email: false

after_success:
  - codecov
