language: c

branches:
  only:
    - master

install:
  - source devtools/ci/install.sh
  - export PYTHONUNBUFFERED=true

script:
  # this builds the binary, unpacks it, and runs the tests
  - conda build devtools/conda-recipe

env:
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.4  CONDA_PY=34

  global:
    # encrypted BINSTAR_TOKEN for push of dev package to binstar
    - secure: I/lGWwQgnRX7UuikhyK0PCwRXIyzT5M5hU0ojnNsNBTiTf0CCj4qJK5K+aBI4yrLIKRAF+uHKYEhnIdA3rTi6Mk4FdM9DEecv9+9m2UDbB1mQcuYmimoaHG90lVXXzfP7wsA05JbshOEQPSUocQvmGksN2NyX+lu79NUsOQRaPs=

after_success:
  - echo "after_success"
  - source devtools/ci/after_sucess.sh
