language: c
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - g++
      - gfortran
      - valgrind
      - csh
      - g++-multilib
      - gcc-multilib

branches:
  only:
    - master

before_install:
  # Configure environment.
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true
  - export REPO_SLUG="choderalab/openmoltools"
  # Unpack encrypted OpenEye license file
  - if [ "$TRAVIS_REPO_SLUG" == "$REPO_SLUG" ]; then openssl aes-256-cbc -K $encrypted_82d3518ff79e_key -iv $encrypted_82d3518ff79e_iv -in oe_license.txt.enc -out $HOME/oe_license.txt -d; fi
  - if [ "$TRAVIS_REPO_SLUG" != "$REPO_SLUG" ]; then echo "OpenEye license will not be installed in pull request."; fi

install:

script:
  # Add omnia channel
  - conda config --add channels ${ORGNAME}
  # Build conda dev package
  - conda build devtools/conda-recipe
  # Install package prerequisites
  - conda install --yes --quiet pip nose nose-timer
  - conda config --add channels https://conda.anaconda.org/rdkit
  - conda install --yes --quiet packmol
  - pip install $OPENEYE_CHANNEL openeye-toolkits
  # Test the package
  - source activate _test
  - cd devtools && nosetests $PACKAGENAME --nocapture --verbosity=2 --with-doctest --with-timer -a '!slow' && cd ..

env:
  matrix:
    # OpenEye production
    - python=2.7  CONDA_PY=27  OPENEYE_CHANNEL="-i https://pypi.anaconda.org/openeye/channel/main/simple"
    - python=3.3  CONDA_PY=33  OPENEYE_CHANNEL="-i https://pypi.anaconda.org/openeye/channel/main/simple"
    - python=3.4  CONDA_PY=34  OPENEYE_CHANNEL="-i https://pypi.anaconda.org/openeye/channel/main/simple"
    # OpenEye beta
    - python=2.7  CONDA_PY=27  OPENEYE_CHANNEL="--pre -i https://pypi.anaconda.org/openeye/channel/beta/simple"
    - python=3.3  CONDA_PY=33  OPENEYE_CHANNEL="--pre -i https://pypi.anaconda.org/openeye/channel/beta/simple"
    - python=3.4  CONDA_PY=34  OPENEYE_CHANNEL="--pre -i https://pypi.anaconda.org/openeye/channel/beta/simple"

  global:
    - ORGNAME="omnia"
    - PACKAGENAME="openmoltools"
    # Location of decrypted OpenEye license file
    - OE_LICENSE="$HOME/oe_license.txt"
    # encrypted BINSTAR_TOKEN for push of dev package to binstar
    - secure: "gHW0bvR0blzHALWiODT0t+eg2tpXXIx8uR3ZNFjldDbuLqcGRs0UCZzy2J42/Yl1OHcjkN4SRZGz1EBsF6DRSI9XbSxOy/FH3kwZwr9ROOBYQ50/6JLwsN2iZnw6EPpjfpx/1pehRu49ZKU3tM8N7MA61OR/dm8ExAynSxJHZME="

after_success:
  - echo "after_success"
  - source devtools/travis-ci/after_success.sh
