# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

language: python

jobs:
  include:
    # Extra includes for OSX since python language is not available by default on OSX
    - os: linux
      language: generic
      env: PYTHON_VER=3.6 OPENMM_CHANNEL=omnia
    - os: linux
      language: generic
      env: PYTHON_VER=3.7 OPENMM_CHANNEL=omnia
    - os: osx
      language: generic
      env: PYTHON_VER=3.6 OPENMM_CHANNEL=omnia
    - os: osx
      language: generic
      env: PYTHON_VER=3.7 OPENMM_CHANNEL=omnia
    - os: linux
      language: generic
      env: PYTHON_VER=3.6 OPENMM_CHANNEL="omnia-dev"
    - os: linux
      language: generic
      env: PYTHON_VER=3.7 OPENMM_CHANNEL="omnia-dev"

env:
  global:
    # Location of decrypted OpenEye license file
    - OE_LICENSE="$HOME/oe_license.txt"
    # encrypted BINSTAR_TOKEN for push of dev package to binstar
    - secure: "S9I5imZ0CJdwfhHzy+Beh8NTFm2ZYpMFCLgvBYT/UsifIKlGynUK2xGi7bDnHLpslT45FUMmjzdpf2QNrfbivVJgiSDTQJc1GCIqGFFKFqerJEEYUkXlBxvWNO+poSOMIzkJqd7xsTodt4CYhGJM1dT6ocaSM7UJgAErrcRJfLo="

branches:
  only:
    - master

before_install:
  # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a
  # Install Conda and dependencies
  - source devtools/travis-ci/install.sh
  - python -V
  # Unpack encrypted OpenEye license file
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ] ; then openssl aes-256-cbc -K $encrypted_751d8ffa39c6_key -iv $encrypted_751d8ffa39c6_iv -in oe_license.txt.enc -out $HOME/oe_license.txt -d; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" == false ] ; then echo "OpenEye license will not be installed in pull request."; fi

install:
  # Create test environment for package
  - conda create --yes -n test python=$PYTHON_VER pip pytest pytest-cov
  - source activate test
  - conda install --yes codecov  # Only available in conda-forge channel or pip
  # Install the OpenEye toolkit
  - conda install --yes -c openeye openeye-toolkits && python -c "import openeye; print(openeye.__version__)"
  # Install other testing dependencies
  - conda install --yes --quiet nose nose-timer
  - echo conda install --yes -c $OPENMM_CHANNEL openmm
  - conda install --yes -c $OPENMM_CHANNEL openmm
  - conda install --yes --quiet openmmtools
  - conda install --yes --quiet packmol
  - conda install --yes --quiet rdkit
  # Build the conda package
  - conda build --python=$PYTHON_VER devtools/conda-recipe
  - conda install --yes --use-local openmoltools-dev

script:
  - nosetests --nocapture openmoltools/tests/test_forcefield_generators.py
  - pytest -v --cov=openmoltools --cov-config setup.cfg openmoltools/tests/

notifications:
  email: false

after_success:
  - codecov
