package:
  name: gaff2xml
  version: !!str dev


requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - mdtraj-dev

  run:
    - python
    - pandas
    - scipy
    - mdtraj-dev    

about:
  home: https://github.com/choderalab/gaff2xml
  license: GNU Lesser General Public License v2 or later (LGPLv2+)

