package:
  name: moltools
  version: !!str dev

#source:
#  fn: master.zip
#  url: https://github.com/choderalab/moltools/archive/master.zip

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - mdtraj
    - numpy
    - scipy
    - pandas    
    - openmm
    - ambermini
#    - rdkit    # rdkit is an optional dependency, may want to comment this out for the release version.
  run:
    - python
    - setuptools
    - pandas
    - six
    - mdtraj
    - numpydoc
    - scipy
    - openmm
    - ambermini
#    - rdkit    # rdkit is an optional dependency, may want to comment this out for the release version.

test:
  requires:
    - nose
  imports:
    - moltools
  commands:
    - nosetests moltools -v -a '!slow'

about:
  home: https://github.com/choderalab/moltools
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
