package:
  name: gaff2xml-dev
  version: !!str 3.0.0

#source:
#  fn: master.zip
#  url: https://github.com/choderalab/gaff2xml/archive/master.zip

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - mdtraj
    - numpy
    - scipy
    - openmm    
    - ambermini
  run:
    - python
    - setuptools
    - pandas
    - six
    - mdtraj
    - numpydoc
    - scipy
    - openmm    
    - ambermini    

test:
  requires:
    - nose
  imports:
    - gaff2xml
  commands:
    - nosetests gaff2xml -v

about:
  home: https://github.com/choderalab/gaff2xml
  license: GNU Lesser General Public License v2 or later (LGPLv2+)

