package:
  name: openmoltools-dev
  version: 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - six
    - numpy
    - cython
  run:
    - python
    - setuptools
    - pandas
    - six
    - mdtraj
    - numpy
    - numpydoc
    - scipy
    - openmm
    - pytables
    - ambermini # revisit whether we want ambertools or ambermini
    - parmed    # want latest parmed installed separately from ambertools/ambermini
    - tinydb   # for caching antechamber-generated force fields for small molecules
    - networkx # for matching OEMols with residues
    - packmol   # optional dependency, but easy to include
    - openmmtools # optional dependency, but easy to include
    - rdkit    # optional dependency, but easy to include

test:
  requires:
    - nose
    - openmmtools
  imports:
    - openmoltools
  #commands:
  #  - nosetests openmoltools -v -a '!slow'

about:
  home: https://github.com/choderalab/openmoltools
  license: MIT License
